### ISSUE TITLE
【后端】 API维护工作

### ISSUE THREAD

**Issue by Momoyeyu** [Momoyeyu/CTF-Website#14]
# API维护工作
- [x] 将 API 的 response 标准化
- [x] 根据新的标准重写 api 的 exception 逻辑
- [x] 对新的 api 进行测试
- [x] api 的参数修改同步至文档

# 进度 by 苏俊杰
## 2023-10-29
- 大部分 api 的 response 已经标准化
- 部分 api 的 exception 逻辑重写
- api 做了一些重组

#### Tasks
1. list_all()    // 新
2. list_type()   // 改动
3. query_one()   // 改动

#### Answer
1. commit_flag()
2. download_attachment()
3. list_solved()  // 新
